"""initial business schema

Revision ID: e9aa6f64ae98
Revises:
Create Date: 2026-07-16 06:28:47.247019
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

revision: str = "e9aa6f64ae98"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "branches",
        sa.Column(
            "id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), "sqlite"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_branches_name", "branches", ["name"], unique=False)
    op.create_table(
        "employees",
        sa.Column(
            "id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("employee_code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), "sqlite"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("employee_code"),
    )
    op.create_table(
        "users",
        sa.Column(
            "id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("display_name", sa.String(length=150), nullable=False),
        sa.Column("phone", sa.CHAR(length=10), nullable=False),
        sa.Column("pin_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "cashier", name="userrole", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("is_primary_admin", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "disabled", name="entitystatus", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column(
            "preferred_language",
            sa.Enum("ar", "en", name="language", native_enum=False, length=5),
            nullable=False,
        ),
        sa.Column(
            "branch_id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "failed_login_attempts",
            mysql.TINYINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "locked_until",
            mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "last_login_at",
            mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "active_cashier_branch_id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            sa.Computed(
                "CASE WHEN role = 'cashier' AND status = 'active' THEN branch_id ELSE NULL END",
                persisted=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "primary_admin_guard",
            sa.Integer(),
            sa.Computed("CASE WHEN is_primary_admin = 1 THEN 1 ELSE NULL END", persisted=True),
            nullable=True,
        ),
        sa.CheckConstraint(
            "(role = 'cashier' AND branch_id IS NOT NULL AND is_primary_admin = 0) OR (role = 'admin' AND branch_id IS NULL)",
            name="ck_user_role_branch",
        ),
        sa.CheckConstraint("phone REGEXP '^05[0-9]{8}$'", name="ck_users_phone_format"),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("active_cashier_branch_id", name="uq_active_cashier_branch"),
        sa.UniqueConstraint("phone", name="uq_users_phone"),
        sa.UniqueConstraint("primary_admin_guard", name="uq_primary_admin_guard"),
    )
    op.create_table(
        "audit_logs",
        sa.Column(
            "id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "actor_user_id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=60), nullable=False),
        sa.Column(
            "entity_id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "branch_id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("old_values", sa.JSON(), nullable=True),
        sa.Column("new_values", sa.JSON(), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column(
            "occurred_at",
            mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), "sqlite"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_actor", "audit_logs", ["actor_user_id", "occurred_at"], unique=False)
    op.create_index(
        "ix_audit_branch_date", "audit_logs", ["branch_id", "occurred_at"], unique=False
    )
    op.create_index(
        "ix_audit_entity", "audit_logs", ["entity_type", "entity_id", "occurred_at"], unique=False
    )
    op.create_table(
        "branch_closure_days",
        sa.Column(
            "id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "branch_id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("work_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("closed", "reopened", name="closurestatus", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("close_reason", sa.String(length=500), nullable=False),
        sa.Column(
            "closed_by_user_id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "closed_at", mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), "sqlite"), nullable=False
        ),
        sa.Column("reopen_reason", sa.String(length=500), nullable=True),
        sa.Column(
            "reopened_by_user_id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "reopened_at",
            mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), "sqlite"),
            nullable=True,
        ),
        sa.CheckConstraint(
            "(status = 'closed' AND reopen_reason IS NULL AND reopened_by_user_id IS NULL AND reopened_at IS NULL) OR (status = 'reopened' AND reopen_reason IS NOT NULL AND reopened_by_user_id IS NOT NULL AND reopened_at IS NOT NULL)",
            name="ck_branch_closure_state",
        ),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["closed_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["reopened_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("branch_id", "work_date", name="uq_branch_closure_date"),
    )
    op.create_index(
        "ix_branch_closure_date", "branch_closure_days", ["work_date", "branch_id"], unique=False
    )
    op.create_table(
        "branch_daily_settlements",
        sa.Column(
            "id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "branch_id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("work_date", sa.Date(), nullable=False),
        sa.Column("employees_sales_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("cash_total", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("bank_total", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column(
            "branch_income_total",
            sa.Numeric(precision=14, scale=2),
            sa.Computed("cash_total + bank_total", persisted=True),
            nullable=True,
        ),
        sa.Column("reconciliation_note", sa.String(length=500), nullable=True),
        sa.Column(
            "settlement_submitted_at",
            mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "created_by_user_id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "cashier_updated_by_user_id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "admin_updated_by_user_id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "cashier_updated_at",
            mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "admin_updated_at",
            mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "employees_total_updated_at",
            mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "row_created_at",
            mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), "sqlite"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(cash_total IS NULL AND bank_total IS NULL AND settlement_submitted_at IS NULL AND created_by_user_id IS NULL) OR (cash_total IS NOT NULL AND bank_total IS NOT NULL AND settlement_submitted_at IS NOT NULL AND created_by_user_id IS NOT NULL)",
            name="ck_settlement_submission",
        ),
        sa.CheckConstraint("bank_total IS NULL OR bank_total >= 0", name="ck_bank_nonnegative"),
        sa.CheckConstraint("cash_total IS NULL OR cash_total >= 0", name="ck_cash_nonnegative"),
        sa.ForeignKeyConstraint(["admin_updated_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["cashier_updated_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("branch_id", "work_date", name="uq_settlement_branch_date"),
    )
    op.create_index("ix_settlements_date", "branch_daily_settlements", ["work_date"], unique=False)
    op.create_table(
        "branch_status_periods",
        sa.Column(
            "id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "branch_id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("active", "disabled", name="entitystatus", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column(
            "created_by_user_id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), "sqlite"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to >= effective_from", name="ck_branch_status_dates"
        ),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("branch_id", "effective_from", name="uq_branch_status_start"),
    )
    op.create_index(
        "ix_branch_status_lookup",
        "branch_status_periods",
        ["branch_id", "effective_from", "effective_to"],
        unique=False,
    )
    op.create_table(
        "daily_sales",
        sa.Column(
            "id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "branch_id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "employee_id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("work_date", sa.Date(), nullable=False),
        sa.Column(
            "service_count",
            mysql.INTEGER(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("sales_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "created_by_user_id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "cashier_updated_by_user_id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "admin_updated_by_user_id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "admin_locked_at",
            mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "admin_locked_by_user_id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), "sqlite"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(admin_locked_at IS NULL AND admin_locked_by_user_id IS NULL) OR (admin_locked_at IS NOT NULL AND admin_locked_by_user_id IS NOT NULL)",
            name="ck_daily_sale_admin_lock",
        ),
        sa.CheckConstraint("sales_total >= 0", name="ck_daily_sale_total_nonnegative"),
        sa.CheckConstraint("service_count >= 0", name="ck_daily_sale_services_nonnegative"),
        sa.ForeignKeyConstraint(["admin_locked_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["admin_updated_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["cashier_updated_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("employee_id", "work_date", name="uq_daily_sale_employee_date"),
    )
    op.create_index(
        "ix_daily_sales_branch_date", "daily_sales", ["branch_id", "work_date"], unique=False
    )
    op.create_index("ix_daily_sales_date", "daily_sales", ["work_date"], unique=False)
    op.create_table(
        "employee_branch_assignments",
        sa.Column(
            "id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "employee_id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "branch_id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "assignment_status",
            sa.Enum("active", "disabled", name="entitystatus", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column(
            "created_by_user_id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), "sqlite"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to >= effective_from",
            name="ck_employee_assignment_dates",
        ),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("employee_id", "effective_from", name="uq_employee_assignment_start"),
    )
    op.create_index(
        "ix_employee_assignment_history",
        "employee_branch_assignments",
        ["employee_id", "effective_from", "effective_to"],
        unique=False,
    )
    op.create_index(
        "ix_employee_assignment_required",
        "employee_branch_assignments",
        ["branch_id", "assignment_status", "effective_from", "effective_to"],
        unique=False,
    )
    op.create_table(
        "refresh_sessions",
        sa.Column(
            "id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "user_id",
            mysql.BIGINT(unsigned=True).with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "last_activity_at",
            mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "absolute_expires_at",
            mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "revoked_at", mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), "sqlite"), nullable=True
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash", name="uq_refresh_token_hash"),
    )
    op.create_index(
        "ix_refresh_sessions_user_active",
        "refresh_sessions",
        ["user_id", "revoked_at", "absolute_expires_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_refresh_sessions_user_active", table_name="refresh_sessions")
    op.drop_table("refresh_sessions")
    op.drop_index("ix_employee_assignment_required", table_name="employee_branch_assignments")
    op.drop_index("ix_employee_assignment_history", table_name="employee_branch_assignments")
    op.drop_table("employee_branch_assignments")
    op.drop_index("ix_daily_sales_date", table_name="daily_sales")
    op.drop_index("ix_daily_sales_branch_date", table_name="daily_sales")
    op.drop_table("daily_sales")
    op.drop_index("ix_branch_status_lookup", table_name="branch_status_periods")
    op.drop_table("branch_status_periods")
    op.drop_index("ix_settlements_date", table_name="branch_daily_settlements")
    op.drop_table("branch_daily_settlements")
    op.drop_index("ix_branch_closure_date", table_name="branch_closure_days")
    op.drop_table("branch_closure_days")
    op.drop_index("ix_audit_entity", table_name="audit_logs")
    op.drop_index("ix_audit_branch_date", table_name="audit_logs")
    op.drop_index("ix_audit_actor", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("users")
    op.drop_table("employees")
    op.drop_index("ix_branches_name", table_name="branches")
    op.drop_table("branches")
    # ### end Alembic commands ###
